version: "3.1"
services:
  nginx:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx/
      - ./etc/ssl:/var/ssl
    depends_on:
      - horizon
      - stream
  horizon:
    image: registry.evertrust.io/horizon:2.4.4
    volumes:
      - ./licenses:/var/horizon/license/
    environment:
      MONGODB_URI: mongodb://mongo:27017/horizon
      APPLICATION_SECRET: evertrust
      EVENT_SEAL_SECRET: evertrust
      VAULT_TYPE: ssv
      VAULT_MASTER_PASSWORD: evertrust
      ACME_URL_SCHEME: http
      HOSTS_ALLOWED.0: .
      LICENSE_PATH: /var/horizon/license/horizon.lic
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8558/ready" ]
      interval: 10s
      timeout: 60s
      retries: 7
  stream:
    image: registry.evertrust.io/stream:1.1.3
    volumes:
      - ./licenses:/var/stream/license/
      - ./etc/stream:/var/stream/etc/
    environment:
      MONGODB_URI: mongodb://mongo:27017/stream
      APPLICATION_SECRET: evertrust
      EVENT_SEAL_SECRET: evertrust
      VAULT_TYPE: ssv
      VAULT_MASTER_PASSWORD: evertrust
      ACME_URL_SCHEME: http
      HOSTS_ALLOWED.0: .
      LICENSE_PATH: /var/stream/license/stream.lic
      KEYSET_PATH: /var/stream/etc/keyset.json
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8558/ready" ]
      interval: 10s
      timeout: 60s
      retries: 7
  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
  webserver:
    build:
      context: ./webserver
      args:
        REPOSITORY_USER: ${REPOSITORY_USER}
        REPOSITORY_PASSWORD: ${REPOSITORY_PASSWORD}
    privileged: true
    ports:
      - "8443:443"