- hosts: all
  become: yes
  vars:
    - domain: demo-ansible.lab
  tasks:
  - name: Updating APT cache
    apt: update_cache=yes  
  
  - name: Installing apache
    apt: 
      name: apache2 
      state: latest

  - name: Enabling the SSL module
    command: "a2enmod ssl"
    become: true
    become_user: root
  
  - name: Enrolling a certificate on Horizon for domain {{ domain }}
    evertrust.horizon.horizon_enroll:
      endpoint: "{{ horizon_endpoint }}"
      mode: "centralized"
      key_type: "rsa-2048"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      profile: "{{ profile }}"
      subject:
        cn.1: "{{ domain }}"
      sans:
        dnsname:
          - "{{ domain }}"
          - "www.{{ domain }}"
      team: "RSSI"
      labels:
        AppCode: "APP1234"
        BusinessUnit: "DSI"
        Environment: "PREPROD"
        SecurityValidationGroup: "RSSI_FR"
      contact_email: "demo@evertrust.fr"
    register: enrolled_certificate

  - name: Creating the SSL directory
    file:
      path: /etc/apache2/ssl
      state: directory
      mode: '0775'
      owner: "www-data"
      group: "www-data"

  - name: Uploading the {{ domain }} certificate
    copy:
      content: "{{ enrolled_certificate['certificate']['certificate'] }}"
      dest: "/etc/apache2/ssl/{{ domain }}.crt"
      mode: '0775'
      owner: "www-data"
      group: "www-data"
    
  - name: Uploading the {{ domain }} private key
    copy:
      content: "{{ enrolled_certificate['key'] }}"
      dest: "/etc/apache2/ssl/{{ domain }}.key"
      mode: '0660'
      owner: "www-data"
      group: "www-data"

  - name: Creating the {{ domain }} webroot directory
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "www-data"
      group: "www-data"

  - name: Deploying the {{ domain }} index page
    template:
      src: ../templates/index.html.j2
      dest: "/var/www/{{ domain }}/index.html"
      owner: "www-data"
      group: "www-data"
      mode: '0644'

  - name: Uploading the {{ domain }} site config
    template:
      src: ../templates/apache.conf.j2
      dest: "/etc/apache2/sites-available/{{ domain }}.conf"
      owner: root
      group: root
      mode: '0644'

  - name: Activating SSL for {{ domain }}
    command: "a2ensite {{ domain }}"
    become: true
    become_user: root

  - name: Restarting Apache
    service:
      name: apache2
      state: restarted