- hosts: all
  become: yes
  vars:
    - domain: demo-ansible.lab
    - renewal_period: 30
  tasks:
  - name: Retrieving current certificate
    shell: "cat /etc/apache2/ssl/{{ domain }}.crt"
    register: current_certificate
  
  - name: Looking up for current certificate in Horizon
    set_fact:
      current_lookup_result: >-
        {{ query('evertrust.horizon.horizon_lookup', certificate_pem=current_certificate['stdout'], x_api_id=api_id, x_api_key=api_key, endpoint=horizon_endpoint) }}

  - name: Calculating certificate renewal date
    set_fact:
      should_renew: "{{(a|int / 1000) - (c|int *86400) < b|int}}"
    vars:
      a: "{{ current_lookup_result['notAfter'] }}"
      b: "{{ ansible_date_time.epoch }}"
      c: "{{ renewal_period }}"

  - name: Renewing certificate if within its renewal period
    evertrust.horizon.horizon_enroll:
      endpoint: "{{ horizon_endpoint }}"
      mode: "centralized"
      key_type: "rsa-2048"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      profile: "{{ profile }}"
      subject:
        cn.1: "{{ domain }}"
      sans:
        dnsname:
          - "{{ domain }}"
          - "www.{{ domain }}"
      team: "RSSI"
      labels:
        AppCode: "APP1234"
        BusinessUnit: "DSI"
        Environment: "PREPROD"
        SecurityValidationGroup: "RSSI_FR"
      contact_email: "demo@evertrust.fr"
    register: enrolled_certificate
    when: should_renew|bool == true

  - name: Uploading the renewed certificate
    copy:
      content: "{{ enrolled_certificate['certificate']['certificate'] }}"
      dest: "/etc/apache2/ssl/{{ domain }}.crt"
    when: should_renew|bool == true

  - name: Uploading the renewed certificate private key
    copy:
      content: "{{ enrolled_certificate['key'] }}"
      dest: "/etc/apache2/ssl/{{ domain }}.key"
    when: should_renew|bool == true

  - name: Redeploying the {{ domain }} index page
    template:
      src: ../templates/index.html.j2
      dest: "/var/www/{{ domain }}/index.html"
      owner: "www-data"
      group: "www-data"
      mode: '0644'
    when: should_renew|bool == true

  - name: Restarting apache2
    service:
      name: apache2
      state: restarted
    when: should_renew|bool == true

  - name: Revoking the previous certificate
    evertrust.horizon.horizon_revoke:
      endpoint: "{{ horizon_endpoint }}"
      x_api_id: "{{ api_id }}"
      x_api_key: "{{ api_key }}"
      certificate_pem: "{{ current_certificate['stdout'] }}"
    when: should_renew|bool == true